### ISSUE TITLE
"Compression"

### ISSUE THREAD

**Issue by cabo** [cose-wg/Charter#8]
The current text about CBOR certificates still uses the term "compression".
That creates an opportunity for confusion with RFC 8879, which I think is detrimental.

**Comment by gselander** [comment]
Agreed, I just noted that too. Would be resolved by map "compression" -> "encoding", etc.. @cabo:  Do you agree?

 I volunteer to do the change.

**Comment by cabo** [comment]
except for the "compression/decompression" case, that works for me.
